#spring:
#  application:
#    name: sleuthSample
#  sleuth:
#    log:
#      json:
#        enabled: true

#logging:
#  pattern:
#    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wex'

spring:
  application:
    # This ends up as the service name in zipkin
    name: ms-sleuth
#  zipkin:
    # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
    # baseUrl: http://192.168.99.100:9411/
#  sleuth:
#    sampler:
#      percentage: 1.0

#sample:
#  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
#    enabled: false